a="Hey user"
b="Welcome"
c="to the world of"
d="python3.7.3"
print("Uppercase")
print(a.upper())
print(b.upper())
print(c.upper())
print(d.upper())
print("lowercase")
print(a.lower())
print(b.lower())
print(c.lower())
print(d.lower())
print("Checking that whether all strings are in uppercase or lowercase")
print(a.isupper())
print(b.isupper())
print(c.isupper())
print(d.isupper())
print(a.islower())
print(b.islower())
print(c.islower())
print(d.islower())
print("Cheching of alphanum function.")
print(a.isalnum())
print(b.isalnum())
print(c.isalnum())
print(d.isalnum())
print("Checking of digits")
print(a.isdigit())
print(b.isdigit())
print(c.isdigit())
print(d.isdigit())
print("a sting starts with He",a.startswith("He"))
print("c string ends with of",c.endswith("of"))
jo="*".join([a,b,c,d])
print(jo)
